import type { Metadata } from "next";
import { cache } from "react";
import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { fetchQuery } from "convex/nextjs";

import { api } from "@/convex/_generated/api";
import { ModeToggle } from "@/components/mode-toggle";
import { renderNoteHtml, noteExcerpt } from "@/lib/note-render";

export const runtime = "nodejs";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";

interface NotePageProps {
  params: Promise<{ slug: string }>;
}

// Deduped across generateMetadata + the page render within one request.
const getDoc = cache((slug: string) =>
  fetchQuery(api.documents.getBySlug, { slug })
);

export async function generateMetadata({
  params,
}: NotePageProps): Promise<Metadata> {
  const { slug } = await params;
  const doc = await getDoc(slug);

  if (!doc) {
    return { title: "Not found" };
  }

  const description = await noteExcerpt(doc.content);
  const url = `${SITE_URL}/notes/${slug}`;

  // OG/Twitter images are generated by opengraph-image.tsx / twitter-image.tsx
  // (Satori) and injected automatically by Next — no need to set them here.
  return {
    title: doc.title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "article",
      title: doc.title,
      description,
      url,
    },
    twitter: {
      card: "summary_large_image",
      title: doc.title,
      description,
    },
  };
}

const NotePage = async ({ params }: NotePageProps) => {
  const { slug } = await params;
  const doc = await getDoc(slug);

  if (!doc) {
    notFound();
  }

  const html = await renderNoteHtml(doc.content);
  const description = await noteExcerpt(doc.content);
  const url = `${SITE_URL}/notes/${slug}`;

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: doc.title,
    description,
    datePublished: new Date(doc._creationTime).toISOString(),
    dateModified: new Date(doc.updatedAt ?? doc._creationTime).toISOString(),
    ...(doc.coverImage ? { image: doc.coverImage } : {}),
    mainEntityOfPage: url,
    author: { "@type": "Person", name: "My Study Notes" },
  };

  return (
    <div className="min-h-full">
      <header className="max-w-3xl mx-auto w-full flex items-center justify-between px-6 py-4">
        <Link href="/" className="text-sm font-semibold">
          My Study Notes
        </Link>
        <ModeToggle />
      </header>

      {doc.coverImage && (
        <div className="relative w-full h-[35vh]">
          <Image
            src={doc.coverImage}
            fill
            alt={doc.title}
            className="object-cover"
            priority
          />
        </div>
      )}

      <article className="max-w-3xl mx-auto px-6 py-10">
        <h1 className="text-4xl font-bold mb-8 flex items-center gap-x-3">
          {doc.icon && <span>{doc.icon}</span>}
          {doc.title}
        </h1>
        <div
          className="prose dark:prose-invert max-w-none"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
    </div>
  );
};

export default NotePage;
